import {spawn} from 'node:child_process';
import fs from 'node:fs';
const [forcedArg,reducedArg,widthArg,fontArg,spacingArg,diagPath,profile,screenshotPath]=process.argv.slice(2);
const width=Number(widthArg),height=14000,fontPercent=Number(fontArg),browser=process.env.BROWSER,pageUrl=process.env.APP_SYN01_URL||'http://127.0.0.1:8765/.tmp/app-syn-01/harness.html',cdpPort=Number(process.env.APP_SYN01_CDP_PORT||9229);
if(!browser)throw new Error('BROWSER not set');const forced=forcedArg==='forced',reduced=reducedArg==='reduced',spacing=spacingArg==='spacing';
fs.rmSync(profile,{recursive:true,force:true});fs.mkdirSync(profile,{recursive:true});
const args=['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage',`--remote-debugging-port=${cdpPort}`,`--user-data-dir=${profile}`,'about:blank'];if(forced)args.splice(args.length-1,0,'--force-high-contrast');
const cp=spawn(browser,args,{stdio:['ignore','ignore','inherit']});const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){for(let i=0;i<400;i++){try{const r=await fetch(`http://127.0.0.1:${cdpPort}/json/version`);if(r.ok)return String(cdpPort)}catch{}await sleep(100)}throw new Error('CDP port unavailable; launcher exit='+cp.exitCode)}
try{
 const p=await port();let target=null;for(let i=0;i<100;i++){try{const r=await fetch(`http://127.0.0.1:${p}/json/new?about%3Ablank`,{method:'PUT'});if(r.ok){target=await r.json();break}}catch{}await sleep(100)}if(!target?.webSocketDebuggerUrl)throw new Error('page target unavailable');
 const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((res,rej)=>{ws.onopen=res;ws.onerror=rej});let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const q=pending.get(m.id);pending.delete(m.id);m.error?q.rej(new Error(JSON.stringify(m.error))):q.res(m.result)}};const send=(method,params={})=>new Promise((res,rej)=>{const n=++id;pending.set(n,{res,rej});ws.send(JSON.stringify({id:n,method,params}))});
 await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false,screenWidth:width,screenHeight:height});
 await send('Emulation.setEmulatedMedia',{media:'',features:[{name:'prefers-reduced-motion',value:reduced?'reduce':'no-preference'}]});
 const nav=await send('Page.navigate',{url:pageUrl});if(nav?.errorText)throw new Error('navigate: '+nav.errorText);
 for(let i=0;i<150;i++){const ev=await send('Runtime.evaluate',{expression:'!!window.__APP_SYN01_API__',returnByValue:true});if(ev?.result?.value)break;if(i===149)throw new Error('APP-SYN-01 API missing');await sleep(100)}
 await send('Runtime.evaluate',{expression:`(()=>{document.documentElement.style.fontSize='${fontPercent}%';document.documentElement.classList.toggle('spacing-stress',${spacing});return true})()`,returnByValue:true});await sleep(80);
 await send('Runtime.evaluate',{expression:'window.__APP_SYN01_API__.replayF1A();window.__APP_SYN01_API__.swapCS2();true',returnByValue:true});await sleep(60);
 const motionEval=await send('Runtime.evaluate',{expression:`(()=>{const s=[...document.querySelectorAll('.surface')].find(x=>!x.classList.contains('no-mot')&&!x.querySelector('.interaction').hidden);const p=s?.querySelectorAll('.peer')[1],a=s?.querySelector('.context-a'),b=s?.querySelector('.context-b');if(!s||!p||!a||!b)return null;const ps=getComputedStyle(p),as=getComputedStyle(a),bs=getComputedStyle(b);return{surface:s.id,peerTransitionDuration:ps.transitionDuration,peerTransitionDelay:ps.transitionDelay,peerTransform:ps.transform,contextATransitionDuration:as.transitionDuration,contextBTransitionDuration:bs.transitionDuration,contextAOpacity:as.opacity,contextBOpacity:bs.opacity}})()`,returnByValue:true});
 await sleep(760);const ev=await send('Runtime.evaluate',{expression:'window.__APP_SYN01_API__.diagnostic()',returnByValue:true});const diag=ev?.result?.value;if(!diag)throw new Error('APP-SYN-01 diagnostic missing');diag.requested={width,forced,reduced,fontPercent,spacing};diag.motionComputed=motionEval?.result?.value||null;
 await send('Runtime.evaluate',{expression:'document.activeElement?.blur();document.body.tabIndex=-1;document.body.focus()',returnByValue:true});const keyboardFocus=[];
 for(let i=0;i<42;i++){await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,nativeVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,nativeVirtualKeyCode:9});await sleep(8);const f=await send('Runtime.evaluate',{expression:`(()=>{const e=document.activeElement;if(!e)return null;const s=e.closest('.surface');const cs=getComputedStyle(e);const w=e.classList?.contains('selected')?getComputedStyle(e,'::before'):null;return{surface:s?.id||null,text:(e.textContent||'').trim(),selected:!!e.classList?.contains('selected'),focusVisible:e.matches?.(':focus-visible')||false,outlineWidth:cs.outlineWidth,outlineStyle:cs.outlineStyle,witnessWidth:w?.width||null,witnessHeight:w?.height||null}})()`,returnByValue:true});keyboardFocus.push(f?.result?.value||null)}diag.keyboardFocus=keyboardFocus;
 const overflowEval=await send('Runtime.evaluate',{expression:`(()=>[...document.querySelectorAll('*')].map((e,i)=>{const r=e.getBoundingClientRect();return{i,tag:e.tagName,id:e.id||'',cls:typeof e.className==='string'?e.className:'',left:r.left,right:r.right,width:r.width,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth}}).filter(x=>x.right>innerWidth+.5||x.left<-.5||x.scrollWidth>x.clientWidth+1).slice(0,240))()`,returnByValue:true});diag.overflowElements=overflowEval?.result?.value||[];
 fs.writeFileSync(diagPath,JSON.stringify(diag)+'\n');if(screenshotPath){const layout=await send('Page.getLayoutMetrics');const cs=layout.cssContentSize||layout.contentSize;const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:Math.ceil(cs.width),height:Math.ceil(cs.height),scale:1}});fs.writeFileSync(screenshotPath,Buffer.from(shot.data,'base64'))}try{ws.send(JSON.stringify({id:++id,method:'Browser.close'}));await sleep(120)}catch{}ws.close();
}finally{cp.kill('SIGTERM');await Promise.race([new Promise(r=>cp.once('exit',r)),sleep(1500)])}
