import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const [mode,widthArg,diagPath,profile,screenshotPath,portArg]=process.argv.slice(2);
const debugPort=Number(portArg||process.env.CDP_PORT||9251),width=Number(widthArg),height=1500,browser=process.env.BROWSER;
if(!browser)throw new Error('BROWSER not set');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),harness=path.join(root,'prototypes','sel-s1','harness.html');
fs.rmSync(profile,{recursive:true,force:true});fs.mkdirSync(profile,{recursive:true});
const args=['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--allow-file-access-from-files','--disable-extensions',`--remote-debugging-port=${debugPort}`,`--user-data-dir=${profile}`,'about:blank'];
if(mode==='forced')args.splice(args.length-1,0,'--force-high-contrast');
const cp=spawn(browser,args,{stdio:['ignore','ignore','inherit']}),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitCDP(){for(let i=0;i<400;i++){try{const r=await fetch(`http://127.0.0.1:${debugPort}/json/version`);if(r.ok)return}catch{}await sleep(100)}throw new Error('CDP unavailable; launcher exit='+cp.exitCode)}
try{await waitCDP();let target=null;for(let i=0;i<100;i++){try{const r=await fetch(`http://127.0.0.1:${debugPort}/json/new?about%3Ablank`,{method:'PUT'});if(r.ok){target=await r.json();break}}catch{}await sleep(100)}if(!target?.webSocketDebuggerUrl)throw new Error('page target unavailable');
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((res,rej)=>{ws.onopen=res;ws.onerror=rej});let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const q=pending.get(m.id);pending.delete(m.id);m.error?q.rej(new Error(JSON.stringify(m.error))):q.res(m.result)}};const send=(method,params={})=>new Promise((res,rej)=>{const n=++id;pending.set(n,{res,rej});ws.send(JSON.stringify({id:n,method,params}))});
await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false,screenWidth:width,screenHeight:height});const nav=await send('Page.navigate',{url:pathToFileURL(harness).href});if(nav?.errorText)throw new Error('navigate: '+nav.errorText);
for(let i=0;i<150;i++){const r=await send('Runtime.evaluate',{expression:'document.readyState+":"+(window.__SEL_S1_META__?.boards||0)',returnByValue:true});if(r?.result?.value==='complete:30')break;await sleep(100)}
const expression=`(()=>{const q=(e,s)=>e.querySelector(s),rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}},near=(a,b,t=.6)=>Math.abs(a-b)<=t,visible=e=>{if(!e)return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};
const boards=[...document.querySelectorAll('.board')],map=new Map(),boardOverflowFailures=[],baseGeometryFailures=[],textMismatchFailures=[],candidateWitnessFailures=[],focusFixtureFailures=[];
for(const b of boards){const key=b.dataset.layout,arr=[...b.querySelectorAll('.char')];if(b.scrollWidth>b.clientWidth+1)boardOverflowFailures.push(b.dataset.family+':'+key);for(const c of arr){if(q(c,'.state-label')?.textContent.trim()!==c.dataset.state||q(c,'.char-name')?.textContent.trim()!==c.dataset.name)textMismatchFailures.push(b.dataset.family+':'+key+':'+c.dataset.index)}if(b.dataset.family==='CNEG')map.set(key,arr.map(c=>({beam:rect(q(c,'.beam')),pool:rect(q(c,'.pool')),hinge:rect(q(c,'.hinge')),name:rect(q(c,'.namebox'))})));}
for(const b of boards){if(!['F1','F2','F3','F4'].includes(b.dataset.family))continue;const ref=map.get(b.dataset.layout),arr=[...b.querySelectorAll('.char')];arr.forEach((c,i)=>{const cur={beam:rect(q(c,'.beam')),pool:rect(q(c,'.pool')),hinge:rect(q(c,'.hinge')),name:rect(q(c,'.namebox'))};for(const part of ['beam','pool','hinge','name'])for(const k of ['x','y','w','h'])if(!near(cur[part][k],ref[i][part][k]))baseGeometryFailures.push(b.dataset.family+':'+b.dataset.layout+':'+i+':'+part+':'+k)});const f=q(b,'.char.focus-fixture');if(f){const ps=getComputedStyle(q(f,'.hinge'),'::before');if(ps.content==='none'||parseFloat(ps.borderTopWidth)<2||ps.borderTopStyle==='none')focusFixtureFailures.push(b.dataset.family+':'+b.dataset.layout)}const s=q(b,'.char.selected');if(s){let ps,ok=false;if(b.dataset.family==='F1'){ps=getComputedStyle(q(s,'.char-name'),'::after');ok=parseFloat(ps.height)>=2&&parseFloat(ps.width)>5}else{ps=getComputedStyle(q(s,'.hinge'),'::after');if(b.dataset.family==='F2')ok=parseFloat(ps.width)>=37&&parseFloat(ps.height)>=3;if(b.dataset.family==='F3')ok=parseFloat(ps.width)>=3&&parseFloat(ps.height)>=25;if(b.dataset.family==='F4')ok=parseFloat(ps.width)>10&&parseFloat(ps.borderBottomWidth)>=2}if(!ok)candidateWitnessFailures.push(b.dataset.family+':'+b.dataset.layout)}}
return{schema:'kymaean.sel-s1.browser-diagnostic.v1',forcedColors:matchMedia('(forced-colors: active)').matches,viewport:{innerWidth,scrollWidth:document.documentElement.scrollWidth},counts:{families:new Set(boards.map(b=>b.dataset.family)).size,boards:boards.length,characters:document.querySelectorAll('.char').length,selected:document.querySelectorAll('.char.selected').length,focusFixtures:document.querySelectorAll('.char.focus-fixture').length,keyboardTargets:document.querySelectorAll('.char[tabindex="0"]').length},boardOverflowFailures,baseGeometryFailures,textMismatchFailures,candidateWitnessFailures,focusFixtureFailures};})()`;
const ev=await send('Runtime.evaluate',{expression,returnByValue:true});const diag=ev?.result?.value;if(!diag)throw new Error('SEL-S1 diagnostic missing');
await send('Runtime.evaluate',{expression:'document.activeElement?.blur();window.scrollTo(0,0);',returnByValue:true});const keyboardFocus=[];
for(let i=0;i<12;i++){await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,nativeVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,nativeVirtualKeyCode:9});await sleep(25);const r=await send('Runtime.evaluate',{expression:`(()=>{const e=document.activeElement;if(!e?.classList?.contains('char'))return null;const b=e.closest('.board'),h=e.querySelector('.hinge'),p=getComputedStyle(h,'::before');const n=getComputedStyle(e.querySelector('.namebox'));return{family:b.dataset.family,layout:b.dataset.layout,name:e.dataset.name,focusVisible:e.matches(':focus-visible'),pseudoContent:p.content,borderWidth:parseFloat(p.borderTopWidth)||0,borderStyle:p.borderTopStyle,nameBorderWidth:parseFloat(n.borderTopWidth)||0,nameBorderStyle:n.borderTopStyle}})()`,returnByValue:true});keyboardFocus.push(r?.result?.value||null)}
diag.keyboardFocus=keyboardFocus;fs.writeFileSync(diagPath,JSON.stringify(diag,null,2)+'\n');
if(screenshotPath){const layout=await send('Page.getLayoutMetrics'),cs=layout.cssContentSize||layout.contentSize,shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:Math.ceil(cs.width),height:Math.ceil(cs.height),scale:1}});fs.writeFileSync(screenshotPath,Buffer.from(shot.data,'base64'))}
ws.send(JSON.stringify({id:++id,method:'Browser.close'}));await sleep(300);try{ws.close()}catch{}
}finally{cp.kill('SIGTERM');await Promise.race([new Promise(r=>cp.once('exit',r)),sleep(1500)])}
